#ifndef _MSP430QUANTOCONSTS_H
#define _MSP430QUANTOCONSTS_H
#include "activity.h"
//Quanto: these are the primary proxy activities for each
//         interrupt that TinyOS uses from the MSP430.
enum {
    QUANTO_ACTIVITY(PXY_ADC)     = NEW_QUANTO_ACTIVITY_ID,
    QUANTO_ACTIVITY(PXY_DACDMA)  = NEW_QUANTO_ACTIVITY_ID,    
    QUANTO_ACTIVITY(PXY_NMI)     = NEW_QUANTO_ACTIVITY_ID,
    QUANTO_ACTIVITY(PXY_PORT1)   = NEW_QUANTO_ACTIVITY_ID,
    QUANTO_ACTIVITY(PXY_PORT2)   = NEW_QUANTO_ACTIVITY_ID,
    QUANTO_ACTIVITY(PXY_TIMERA0) = NEW_QUANTO_ACTIVITY_ID,
    QUANTO_ACTIVITY(PXY_TIMERA1) = NEW_QUANTO_ACTIVITY_ID,
    QUANTO_ACTIVITY(PXY_TIMERB0) = NEW_QUANTO_ACTIVITY_ID,
    QUANTO_ACTIVITY(PXY_TIMERB1) = NEW_QUANTO_ACTIVITY_ID,
    QUANTO_ACTIVITY(PXY_UART0RX) = NEW_QUANTO_ACTIVITY_ID,
    QUANTO_ACTIVITY(PXY_UART0TX) = NEW_QUANTO_ACTIVITY_ID,
    QUANTO_ACTIVITY(PXY_UART1RX) = NEW_QUANTO_ACTIVITY_ID,
    QUANTO_ACTIVITY(PXY_UART1TX) = NEW_QUANTO_ACTIVITY_ID,
};
#endif

